// <auto-generated />
namespace UniversityCourseAndResultManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class modelchangedstudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelchangedstudent));
        
        string IMigrationMetadata.Id
        {
            get { return "201912210452040_model changed student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
